#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_parking_system1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Car ReservationDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_Account(TBL_Account instance);
    partial void UpdateTBL_Account(TBL_Account instance);
    partial void DeleteTBL_Account(TBL_Account instance);
    partial void InsertTable_slot(Table_slot instance);
    partial void UpdateTable_slot(Table_slot instance);
    partial void DeleteTable_slot(Table_slot instance);
    partial void InsertTable_arrival(Table_arrival instance);
    partial void UpdateTable_arrival(Table_arrival instance);
    partial void DeleteTable_arrival(Table_arrival instance);
    partial void InsertTable_departure(Table_departure instance);
    partial void UpdateTable_departure(Table_departure instance);
    partial void DeleteTable_departure(Table_departure instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Car_parking_system1.Properties.Settings.Default.Car_ReservationDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_Account> TBL_Accounts
		{
			get
			{
				return this.GetTable<TBL_Account>();
			}
		}
		
		public System.Data.Linq.Table<Table_slot> Table_slots
		{
			get
			{
				return this.GetTable<Table_slot>();
			}
		}
		
		public System.Data.Linq.Table<Table_arrival> Table_arrivals
		{
			get
			{
				return this.GetTable<Table_arrival>();
			}
		}
		
		public System.Data.Linq.Table<Table_departure> Table_departures
		{
			get
			{
				return this.GetTable<Table_departure>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Account")]
	public partial class TBL_Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _UserName;
		
		private string _Password;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public TBL_Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(30)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(30)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_slots")]
	public partial class Table_slot : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _SLOT__;
		
		private string _Location;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSLOT__Changing(string value);
    partial void OnSLOT__Changed();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    #endregion
		
		public Table_slot()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SLOT_#", Storage="_SLOT__", DbType="NVarChar(30)")]
		public string SLOT__
		{
			get
			{
				return this._SLOT__;
			}
			set
			{
				if ((this._SLOT__ != value))
				{
					this.OnSLOT__Changing(value);
					this.SendPropertyChanging();
					this._SLOT__ = value;
					this.SendPropertyChanged("SLOT__");
					this.OnSLOT__Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_arrival")]
	public partial class Table_arrival : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Driver_name;
		
		private string _Car_NO;
		
		private string _duration_time;
		
		private string _selected_slots;
		
		private string _category;
		
		private System.Nullable<System.DateTime> _arrival_time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDriver_nameChanging(string value);
    partial void OnDriver_nameChanged();
    partial void OnCar_NOChanging(string value);
    partial void OnCar_NOChanged();
    partial void Onduration_timeChanging(string value);
    partial void Onduration_timeChanged();
    partial void Onselected_slotsChanging(string value);
    partial void Onselected_slotsChanged();
    partial void OncategoryChanging(string value);
    partial void OncategoryChanged();
    partial void Onarrival_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onarrival_timeChanged();
    #endregion
		
		public Table_arrival()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Driver_name", DbType="NVarChar(50)")]
		public string Driver_name
		{
			get
			{
				return this._Driver_name;
			}
			set
			{
				if ((this._Driver_name != value))
				{
					this.OnDriver_nameChanging(value);
					this.SendPropertyChanging();
					this._Driver_name = value;
					this.SendPropertyChanged("Driver_name");
					this.OnDriver_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Car_NO", DbType="NVarChar(50)")]
		public string Car_NO
		{
			get
			{
				return this._Car_NO;
			}
			set
			{
				if ((this._Car_NO != value))
				{
					this.OnCar_NOChanging(value);
					this.SendPropertyChanging();
					this._Car_NO = value;
					this.SendPropertyChanged("Car_NO");
					this.OnCar_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration_time", DbType="NVarChar(50)")]
		public string duration_time
		{
			get
			{
				return this._duration_time;
			}
			set
			{
				if ((this._duration_time != value))
				{
					this.Onduration_timeChanging(value);
					this.SendPropertyChanging();
					this._duration_time = value;
					this.SendPropertyChanged("duration_time");
					this.Onduration_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_selected_slots", DbType="NVarChar(50)")]
		public string selected_slots
		{
			get
			{
				return this._selected_slots;
			}
			set
			{
				if ((this._selected_slots != value))
				{
					this.Onselected_slotsChanging(value);
					this.SendPropertyChanging();
					this._selected_slots = value;
					this.SendPropertyChanged("selected_slots");
					this.Onselected_slotsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="NVarChar(50)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this.OncategoryChanging(value);
					this.SendPropertyChanging();
					this._category = value;
					this.SendPropertyChanged("category");
					this.OncategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arrival_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> arrival_time
		{
			get
			{
				return this._arrival_time;
			}
			set
			{
				if ((this._arrival_time != value))
				{
					this.Onarrival_timeChanging(value);
					this.SendPropertyChanging();
					this._arrival_time = value;
					this.SendPropertyChanged("arrival_time");
					this.Onarrival_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_departure")]
	public partial class Table_departure : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Car_No;
		
		private string _Driver_name;
		
		private string _Make_model;
		
		private string _duration_time;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<System.DateTime> _departure_time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCar_NoChanging(string value);
    partial void OnCar_NoChanged();
    partial void OnDriver_nameChanging(string value);
    partial void OnDriver_nameChanged();
    partial void OnMake_modelChanging(string value);
    partial void OnMake_modelChanged();
    partial void Onduration_timeChanging(string value);
    partial void Onduration_timeChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void Ondeparture_timeChanging(System.Nullable<System.DateTime> value);
    partial void Ondeparture_timeChanged();
    #endregion
		
		public Table_departure()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Car_No", DbType="NVarChar(50)")]
		public string Car_No
		{
			get
			{
				return this._Car_No;
			}
			set
			{
				if ((this._Car_No != value))
				{
					this.OnCar_NoChanging(value);
					this.SendPropertyChanging();
					this._Car_No = value;
					this.SendPropertyChanged("Car_No");
					this.OnCar_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Driver_name", DbType="NVarChar(50)")]
		public string Driver_name
		{
			get
			{
				return this._Driver_name;
			}
			set
			{
				if ((this._Driver_name != value))
				{
					this.OnDriver_nameChanging(value);
					this.SendPropertyChanging();
					this._Driver_name = value;
					this.SendPropertyChanged("Driver_name");
					this.OnDriver_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Make/model]", Storage="_Make_model", DbType="NVarChar(50)")]
		public string Make_model
		{
			get
			{
				return this._Make_model;
			}
			set
			{
				if ((this._Make_model != value))
				{
					this.OnMake_modelChanging(value);
					this.SendPropertyChanging();
					this._Make_model = value;
					this.SendPropertyChanged("Make_model");
					this.OnMake_modelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration_time", DbType="NVarChar(50)")]
		public string duration_time
		{
			get
			{
				return this._duration_time;
			}
			set
			{
				if ((this._duration_time != value))
				{
					this.Onduration_timeChanging(value);
					this.SendPropertyChanging();
					this._duration_time = value;
					this.SendPropertyChanged("duration_time");
					this.Onduration_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departure_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> departure_time
		{
			get
			{
				return this._departure_time;
			}
			set
			{
				if ((this._departure_time != value))
				{
					this.Ondeparture_timeChanging(value);
					this.SendPropertyChanging();
					this._departure_time = value;
					this.SendPropertyChanged("departure_time");
					this.Ondeparture_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
